<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminMain.aspx.cs" Inherits="AdminMain" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
    <link href="Theme/Style.css" rel="stylesheet" type="text/css" />
    <div class="Base">
    <form id="form1" runat="server" class="Main_Div">
    <div>
    
      <h1>
         <asp:Menu ID="Menu1" runat="server" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal">
            <Items>
               
               
                <asp:MenuItem Text="Utilizatori" Value="0"></asp:MenuItem>
                <asp:MenuItem Text="Categorii" Value="1"></asp:MenuItem>
                <asp:MenuItem Text="Proiecte" Value="2"></asp:MenuItem>
                <asp:MenuItem Text="Tipuri de activități" Value="3"></asp:MenuItem>
                <asp:MenuItem Text="Mașini" Value="4"></asp:MenuItem>
                <asp:MenuItem  Text="Rapoarte" Value="5"></asp:MenuItem>
                <asp:MenuItem  Text="Schimbă parola" Value="6"></asp:MenuItem>
                
                 
            </Items>
            <staticmenuitemstyle BorderWidth="10px" BorderColor="#6189df"  forecolor="Black" />  
        </asp:Menu>
           </h1>   
      
    
         
           
        <div runat="server" id="ScrollList" class="Main_Menu_div">
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0" >
                
              
           
                   

          
            
           <asp:View ID="ViewUsers" runat="server">
            
              

               <asp:GridView ID="GridViewUsers" runat="server" CssClass="grid" Width="1000px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" DataKeyNames="id" DataSourceID="SqlDataSourceUsers">
                   <Columns>
                      
                      
                       <asp:BoundField DataField="last_name" HeaderText="Nume" SortExpression="last_name" ItemStyle-Width="15%"/>
                        <asp:BoundField DataField="first_name" HeaderText="Prenume" SortExpression="first_name" ItemStyle-Width="15%"/>
                       <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" ItemStyle-Width="25%" />
                       <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" ItemStyle-Width="25%"/>

                       <asp:TemplateField ItemStyle-CssClass="TemplateFieldOneColumn" HeaderText="Rol" ItemStyle-Width="15%">

                         <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelTextRole(Eval("id_role")) %>' />
                         </ItemTemplate>

                       </asp:TemplateField>
                      
                   </Columns>

               </asp:GridView>

               <br/>
                 <asp:Button ID="AddUser" runat="server" Text="ADAUGĂ UTILIZATOR" OnClick="AddUser_Click" CssClass="Main_btn"/>
               
               
              

               <asp:SqlDataSource ID="SqlDataSourceUsers" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Users] order by last_name, first_name"
                  DeleteCommand="delete from [Users] where [id]=@id" >

               </asp:SqlDataSource>
              
          </asp:View>

            
            <asp:View ID="ViewCategories" runat="server">

                <asp:GridView ID="GridViewCtegories" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceCategories" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="70%"/>
                                
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceCategories" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [ProjectCategories] order by name"
                         UpdateCommand="Update [ProjectCategories] set [name]=@name where [id]=@id" DeleteCommand="delete from [ProjectCategories] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddCatgory" runat="server" Text="ADAUGĂ CATEGORIE" Enabled="True"  OnClick="ButtonAddCategory_Click"  CssClass="Main_btn"/>
                
            </asp:View>

            
            <asp:View ID="ViewProjects" runat="server">
               
                   
                        <asp:GridView ID="GridViewProjects" runat="server" CssClass="grid" Width="800px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="40%"/>
                                 <asp:TemplateField ShowHeader="False" HeaderText="Categorie proiect" ItemStyle-Width="40%">
                                 <ItemTemplate>
                                         <asp:Label runat="server" Text='<% #GetLabelTextCategory(Eval("id_category")) %>' />
                                 </ItemTemplate>
                                    </asp:TemplateField>

                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Projects] order by name"
                         UpdateCommand="Update [Projects] set [name]=@name  where [id]=@id" DeleteCommand="delete from [Projects] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                               
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddProject" runat="server" Text="ADAUGĂ PROIECT" Enabled="True"  OnClick="ButtonAddProject_Click"  CssClass="Main_btn"/>
                            
                     
                
            </asp:View>

             <asp:View ID="ViewActivities" runat="server">
               
                   
                        <asp:GridView ID="GridViewActivities" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceActivities" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="70%"/>
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceActivities" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [ActivityTypes] order by name"
                         UpdateCommand="Update [ActivityTypes] set [name]=@name where [id]=@id" DeleteCommand="delete from [ActivityTypes] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddActivity" runat="server" Text="ADAUGĂ TIP DE ACTIVITATE" Enabled="True"  OnClick="ButtonAddActivity_Click" CssClass="Main_btn" />
                     
                
            </asp:View>

             <asp:View ID="ViewCars" runat="server">
               
                   
                        <asp:GridView ID="GridViewCars" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceCars" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="number" HeaderText="Număr de înmatriculare" SortExpression="number" ItemStyle-Width="70%"/>
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceCars" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Cars]"
                         UpdateCommand="Update [Cars] set [number]=@number where [id]=@id" DeleteCommand="delete from [Cars] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddCar" runat="server" Text="ADAUGĂ MAȘINĂ" Enabled="True"  OnClick="ButtonAddCar_Click" CssClass="Main_btn" />
                     
                
            </asp:View>

              <asp:View ID="ViewReports" runat="server">
                
            </asp:View>

             <asp:View ID="ViewChangePassword" runat="server" >
               <asp:Label ID="LabelWrongPassword" runat="server" Text="Parolă greșită!" Visible="False"></asp:Label>
        <p>
            <asp:TextBox ID="TextBoxNewPassword" placeholder="Parolă nouă" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword"></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidatorPassword"  runat="server"
          ControlToValidate="TextBoxNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            
        </p>
                     <p>
            <asp:TextBox ID="TextBoxConfirmNewPassword" placeholder="Confirmă parola nouă" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword" ></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidatorConfirmPassword"  runat="server"
          ControlToValidate="TextBoxConfirmNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            <asp:Label ID="Label1" runat="server" Text="Password mismatch!" Visible="False" CssClass="Register_lbl"></asp:Label>
            <br/>
                         <asp:Label ID="LabelMismatch" runat="server" Text="Password mismatch!" Visible="False" CssClass="Register_lbl"></asp:Label>
                         </p>
                         <asp:Button ID="ButtonSave" runat="server" Text="Salvează" OnClick="ButtonSave_Click" CssClass="Main_btn"/>
        

                 </asp:View>

        </asp:MultiView>
                
            
      
    </div>
        
           <div class="Main_footer" runat="server">
            
            <asp:Button ID="ButtonLogout" runat="server" OnClick="ButtonLogout_Click" Text="Delogare" CausesValidation="false" cssClass="Main_logout_btn"/>
            </div>
    </div>
    </form>
        </div>
</body>
</html>
