<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminMain.aspx.cs" Inherits="AdminMain" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
    <link href="Theme/Style.css" rel="stylesheet" type="text/css" />
    <div class="Base">
    <form id="form1" runat="server" class="Main_Div">
    <div>
    
      <h1>
         <asp:Menu ID="Menu1" runat="server" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal">
            <Items>
               
               
                <asp:MenuItem Text="Utilizatori" Value="0"></asp:MenuItem>
                <asp:MenuItem Text="Categorii" Value="1"></asp:MenuItem>
                <asp:MenuItem Text="Proiecte" Value="2"></asp:MenuItem>
                <asp:MenuItem Text="Tipuri de activități" Value="3"></asp:MenuItem>
                <asp:MenuItem Text="Mașini" Value="4"></asp:MenuItem>
                <asp:MenuItem  Text="Rapoarte ore lucrate" Value="5"></asp:MenuItem>
                <asp:MenuItem  Text="Rapoarte deplasări" Value="6"></asp:MenuItem>
                <asp:MenuItem  Text="Schimbă parola" Value="7"></asp:MenuItem>
                
                 
            </Items>
            <staticmenuitemstyle BorderWidth="10px" BorderColor="#6189df"  forecolor="Black" />  
        </asp:Menu>
           </h1>   
      
    
         
           
        <div runat="server" id="ScrollList" class="Main_Menu_div">
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0" >
                
              
           
                   

          
            
           <asp:View ID="ViewUsers" runat="server">
            
              

               <asp:GridView ID="GridViewUsers" runat="server" CssClass="grid" Width="1000px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" DataKeyNames="id" DataSourceID="SqlDataSourceUsers">
                   <Columns>
                      
                      
                       <asp:BoundField DataField="last_name" HeaderText="Nume" SortExpression="last_name" ItemStyle-Width="15%"/>
                        <asp:BoundField DataField="first_name" HeaderText="Prenume" SortExpression="first_name" ItemStyle-Width="15%"/>
                       <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" ItemStyle-Width="25%" />
                       <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" ItemStyle-Width="25%"/>

                       <asp:TemplateField ItemStyle-CssClass="TemplateFieldOneColumn" HeaderText="Rol" ItemStyle-Width="15%">

                         <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelTextRole(Eval("id_role")) %>' />
                         </ItemTemplate>

                       </asp:TemplateField>
                      
                   </Columns>

               </asp:GridView>

               <br/>
                 <asp:Button ID="AddUser" runat="server" Text="ADAUGĂ UTILIZATOR" OnClick="AddUser_Click" CssClass="Main_btn"/>
               
               
              

               <asp:SqlDataSource ID="SqlDataSourceUsers" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Users] order by last_name, first_name"
                  DeleteCommand="delete from [Users] where [id]=@id" >

               </asp:SqlDataSource>
              
          </asp:View>

            
            <asp:View ID="ViewCategories" runat="server">

                <asp:GridView ID="GridViewCtegories" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceCategories" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="70%"/>
                                
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceCategories" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [ProjectCategories] order by name"
                         UpdateCommand="Update [ProjectCategories] set [name]=@name where [id]=@id" DeleteCommand="delete from [ProjectCategories] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddCatgory" runat="server" Text="ADAUGĂ CATEGORIE" Enabled="True"  OnClick="ButtonAddCategory_Click"  CssClass="Main_btn"/>
                
            </asp:View>

            
            <asp:View ID="ViewProjects" runat="server">
               
                   
                        <asp:GridView ID="GridViewProjects" runat="server" CssClass="grid" Width="800px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="40%"/>
                                 <asp:TemplateField ShowHeader="False" HeaderText="Categorie proiect" ItemStyle-Width="40%">
                                 <ItemTemplate>
                                         <asp:Label runat="server" Text='<% #GetLabelTextCategory(Eval("id_category")) %>' />
                                 </ItemTemplate>
                                    </asp:TemplateField>

                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Projects] order by name"
                         UpdateCommand="Update [Projects] set [name]=@name  where [id]=@id" DeleteCommand="delete from [Projects] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                               
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddProject" runat="server" Text="ADAUGĂ PROIECT" Enabled="True"  OnClick="ButtonAddProject_Click"  CssClass="Main_btn"/>
                            
                     
                
            </asp:View>

             <asp:View ID="ViewActivities" runat="server">
               
                   
                        <asp:GridView ID="GridViewActivities" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceActivities" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="name" HeaderText="Denumire" SortExpression="name" ItemStyle-Width="70%"/>
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceActivities" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [ActivityTypes] order by name"
                         UpdateCommand="Update [ActivityTypes] set [name]=@name where [id]=@id" DeleteCommand="delete from [ActivityTypes] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddActivity" runat="server" Text="ADAUGĂ TIP DE ACTIVITATE" Enabled="True"  OnClick="ButtonAddActivity_Click" CssClass="Main_btn" />
                     
                
            </asp:View>

             <asp:View ID="ViewCars" runat="server">
               
                   
                        <asp:GridView ID="GridViewCars" runat="server" CssClass="grid" Width="700px" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceCars" >
                     

                            <EmptyDataRowStyle CssClass="EmptyData" />
                            <EmptyDataTemplate>

                                <div>

                                        No Data Available

                                </div>
                                     
                                <script>
                                     $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                                </script>

                            </EmptyDataTemplate>
                    
                            <Columns>
                        
                                 <asp:BoundField DataField="number" HeaderText="Număr de înmatriculare" SortExpression="number" ItemStyle-Width="70%"/>
                                 
                            </Columns>

                        </asp:GridView>

                        <asp:SqlDataSource ID="SqlDataSourceCars" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Cars]"
                         UpdateCommand="Update [Cars] set [number]=@number where [id]=@id" DeleteCommand="delete from [Cars] where [id]=@id" >

                         </asp:SqlDataSource>

                
                                <br />
                              
 
                                 
                           
         
                    
                            <asp:Button ID="ButtonAddCar" runat="server" Text="ADAUGĂ MAȘINĂ" Enabled="True"  OnClick="ButtonAddCar_Click" CssClass="Main_btn" />
                     
                
            </asp:View>

              <asp:View ID="ViewReports" runat="server">

          

                  <asp:TextBox ID="TextBoxDataStart" placeholder="DATA" runat="server" CssClass="Log_TextBox"></asp:TextBox>       
        <asp:Calendar ID="Calendar1" runat="server" OnSelectionChanged="Calendar1_SelectionChanged" Visible="False" CssClass="Calendar">
             <TitleStyle BackColor="#6189df" ForeColor="White">
         </TitleStyle>
             <TodayDayStyle BackColor="#6189df" ForeColor="White">
            </TodayDayStyle>
             
        </asp:Calendar>
          
            
        <asp:Button ID="ButtonSelectDateStart" runat="server" Text="Selectare data început" OnClick="ButtonSelectDateStart_Click" CssClass="Main_btn" />
            <asp:Label ID="LabelMissingDateStart" runat="server" Text="*" ForeColor="#FF3300" Visible="False"></asp:Label>


                 <asp:TextBox ID="TextBoxDataFinish" placeholder="DATA" runat="server" CssClass="Log_TextBox"></asp:TextBox>       
        <asp:Calendar ID="Calendar2" runat="server" OnSelectionChanged="Calendar2_SelectionChanged" Visible="False" CssClass="Calendar">
             <TitleStyle BackColor="#6189df" ForeColor="White">
         </TitleStyle>
             <TodayDayStyle BackColor="#6189df" ForeColor="White">
            </TodayDayStyle>
             
        </asp:Calendar>
          
            
        <asp:Button ID="ButtonSelectDateFinish" runat="server" Text="Selectare data sfârșit" OnClick="ButtonSelectDateFinish_Click" CssClass="Main_btn" />
            <asp:Label ID="LabelMissingDateFinish" runat="server" Text="*" ForeColor="#FF3300" Visible="False"></asp:Label>

      
                  <p>
            <asp:Label ID="LabelUser" runat="server" Text="ID Utilizator" CssClass="Label"></asp:Label>
             <asp:DropDownList ID="DropDownList1"  runat="server" CssClass="Dropdown">
        </asp:DropDownList>
        </p>

                   <p>
            <asp:Label ID="LabelType" runat="server" Text="Tip raport" CssClass="Label"></asp:Label>
             <asp:DropDownList ID="DropDownList2"  runat="server" CssClass="Dropdown">
        </asp:DropDownList>
        </p>
        
        <asp:Button ID="ButtonFilter" runat="server" Text="Schimbă raportul" OnClick="ButtonFilter_Click" CssClass="Main_btn" />
                <br/><br/>

                  <canvas id="projects-graph" width="800" height="500"></canvas>

                 
    <script>

       

        $(function () {
            var url=[], label=[];
            
             if (("<%= start_date %>" == null||"<%= start_date %>" == ''||"<%= start_date %>" == 'undefined'||"<%= start_date %>" == '0')&&("<%= finish_date %>" == null||"<%= finish_date %>" == ''||"<%= finish_date %>" == 'undefined'||"<%= finish_date %>" == '0'))
             {
                 if ("<%= report_type %>" == 1) {
                     if ("<%= id_user %>" == 0) {
                         url = "/api/projects";
                         label = "Ore lucrate per proiecte de toți utilizatorii";
                     }
                     else
                     {
                         url = "/api/projects/?id=<%= id_user %>";
                         label = "Ore lucrate per proiecte de utilizatorul <%= id_user %>";
                     }
                 }
                 else
                 {
                     if ("<%= id_user %>" == 0) {
                         url = "api/activities";
                         label = "Ore lucrate per activități de toți utilizatorii";
                     }
                     else {
                         url = "/api/activities/?id=<%= id_user %>";
                         label = "Ore lucrate per activități de utilizatorul <%= id_user %>";
                     }
                 }
               
            }
            else
            {
                 if ("<%= report_type %>" == 1) {
                     if ("<%= id_user %>" == 0) {
                         url = "/api/projects?date_start=<%= start_date %>&date_finish=<%= finish_date %>";
                         label = "Ore lucrate per proiecte de toți utilizatorii între <%= start_date %> și <%= finish_date %>";
                     }
                     else
                     {
                         url = "/api/projects/?id=<%= id_user %>&date_start=<%= start_date %>&date_finish=<%= finish_date %>";
                         label = "Ore lucrate per proiecte de utilizatorul <%= id_user %> între <%= start_date %> și <%= finish_date %>";
                     }
                 }
                 else
                 {
                     if ("<%= id_user %>" == 0) {
                         url = "api/activities?date_start=<%= start_date %>&date_finish=<%= finish_date %>";
                         label = "Ore lucrate per activități de toți utilizatorii între <%= start_date %> și <%= finish_date %>";
                     }
                     else {
                         url = "/api/activities/?id=<%= id_user %>&date_start=<%= start_date %>&date_finish=<%= finish_date %>";
                         label = "Ore lucrate per activități de utilizatorul <%= id_user %> între <%= start_date %> și <%= finish_date %>";
                     }
                 }
            }
          
         
            
            $.getJSON(url, function (result) {
                var labels = [], data = [], colors = [];


                var randomColorGenerator = function () {
                    return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };

                for (var i = 0; i < result.length; i = i + 2) {

                    labels.push(result[i]);
                    data.push(result[i + 1]);
                    colors.push(randomColorGenerator());

        }


                var chartData = {
            labels: labels,
            datasets: [
                      {
            label: label,
            backgroundColor: colors,
            data: data
        }
        ]
        };
                var opt = {
            events: false,
            tooltips: {
            enabled: false
        },
            hover: {
            animationDuration: 0
        },
            scales: {
            yAxes: [{
            ticks: {
            beginAtZero: true
        }
        }]
        },
            animation: {
            duration: 1,
            onComplete: function () {
                            var chartInstance = this.chart,
                                ctx = chartInstance.ctx;
                            ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'bottom';

                            this.data.datasets.forEach(function (dataset, i) {
                                var meta = chartInstance.controller.getDatasetMeta(i);
                                meta.data.forEach(function (bar, index) {
                                    var data = dataset.data[index];
                                    ctx.fillText(data, bar._model.x, bar._model.y - 5);
        });
        });
        }
        }
        };
                var ctx = document.getElementById("projects-graph"),
                    myLineChart = new Chart(ctx, {
            type: 'bar',
            data: chartData,
            options: opt
        })

        });

        })
        
        
    </script>
                
            </asp:View>

             <asp:View ID="ViewReports2" runat="server">
            <asp:TextBox ID="TextBoxDataStart2" placeholder="DATA" runat="server" CssClass="Log_TextBox"></asp:TextBox>       
        <asp:Calendar ID="Calendar12" runat="server" OnSelectionChanged="Calendar12_SelectionChanged" Visible="False" CssClass="Calendar">
             <TitleStyle BackColor="#6189df" ForeColor="White">
         </TitleStyle>
             <TodayDayStyle BackColor="#6189df" ForeColor="White">
            </TodayDayStyle>
             
        </asp:Calendar>
          
            
        <asp:Button ID="ButtonSelectDateStart2" runat="server" Text="Selectare data început" OnClick="ButtonSelectDateStart2_Click" CssClass="Main_btn" />
            <asp:Label ID="LabelMissingDateStart2" runat="server" Text="*" ForeColor="#FF3300" Visible="False"></asp:Label>


                 <asp:TextBox ID="TextBoxDataFinish2" placeholder="DATA" runat="server" CssClass="Log_TextBox"></asp:TextBox>       
        <asp:Calendar ID="Calendar22" runat="server" OnSelectionChanged="Calendar22_SelectionChanged" Visible="False" CssClass="Calendar">
             <TitleStyle BackColor="#6189df" ForeColor="White">
         </TitleStyle>
             <TodayDayStyle BackColor="#6189df" ForeColor="White">
            </TodayDayStyle>
             
        </asp:Calendar>
          
            
        <asp:Button ID="ButtonSelectDateFinish2" runat="server" Text="Selectare data sfârșit" OnClick="ButtonSelectDateFinish2_Click" CssClass="Main_btn" />
            <asp:Label ID="LabelMissingDateFinish2" runat="server" Text="*" ForeColor="#FF3300" Visible="False"></asp:Label>

      
                  <p>
            <asp:Label ID="LabelUser2" runat="server" Text="ID Utilizator" CssClass="Label"></asp:Label>
             <asp:DropDownList ID="DropDownList12"  runat="server" CssClass="Dropdown">
        </asp:DropDownList>
        </p>

                   <p>
            <asp:Label ID="LabelType2" runat="server" Text="Tip raport" CssClass="Label"></asp:Label>
             <asp:DropDownList ID="DropDownList22"  runat="server" CssClass="Dropdown">
        </asp:DropDownList>
        </p>
        
        <asp:Button ID="ButtonFilter2" runat="server" Text="Schimbă raportul" OnClick="ButtonFilter2_Click" CssClass="Main_btn" />
                <br/><br/>

                        <canvas id="drivers-graph" width="800" height="500"></canvas>

                 
    <script>

       

        $(function () {
            var url=[], label=[];
            
             if (("<%= start_date2 %>" == null||"<%= start_date2 %>" == ''||"<%= start_date2 %>" == 'undefined'||"<%= start_date2 %>" == '0')&&("<%= finish_date2 %>" == null||"<%= finish_date2 %>" == ''||"<%= finish_date2 %>" == 'undefined'||"<%= finish_date2 %>" == '0'))
             {
                 if ("<%= report_type2 %>" == 1) {
                     if ("<%= id_user2 %>" == 0) {
                         url = "api/DriverHours";
                         label = "Ore deplasări pentru toți șoferii";
                     }
                     else
                     {
                         url = "api/DriverHours/?id=<%= id_user2 %>";
                         label = "Ore deplasări pentru șoferul <%= id_user2 %>";
                     }
                 }
                 else
                 {
                     if ("<%= id_user2 %>" == 0) {
                         url = "api/DriverKm";
                         label = "Km parcurși de toți șoferii";
                     }
                     else {
                         url = "/api/DriverKm/?id=<%= id_user2 %>";
                         label = "Km parcurși de șoferul <%= id_user2 %>";
                     }
                 }
               
            }
            else
            {
                 if ("<%= report_type2 %>" == 1) {
                     if ("<%= id_user2 %>" == 0) {
                         url = "/api/DriverHours?date_start=<%= start_date2 %>&date_finish=<%= finish_date2 %>";
                         label = "Ore de deplasare pentru toți șoferii între <%= start_date2 %> și <%= finish_date2 %>";
                     }
                     else
                     {
                         url = "/api/DriverHours/?id=<%= id_user2 %>&date_start=<%= start_date2 %>&date_finish=<%= finish_date2 %>";
                         label = "Ore de deplasare ale șoferului <%= id_user2 %> între <%= start_date2 %> și <%= finish_date2 %>";
                     }
                 }
                 else
                 {
                     if ("<%= id_user2 %>" == 0) {
                         url = "api/DriverKm?date_start=<%= start_date2 %>&date_finish=<%= finish_date2 %>";
                         label = "Km parcurși de toți șoferii între <%= start_date2 %> și <%= finish_date2 %>";
                     }
                     else {
                         url = "/api/DriverKm/?id=<%= id_user2 %>&date_start=<%= start_date2 %>&date_finish=<%= finish_date2 %>";
                         label = "Km parcurși de către șoferul <%= id_user2 %> între <%= start_date2 %> și <%= finish_date2 %>";
                     }
                 }
            }
          
         
            
            $.getJSON(url, function (result) {
                var labels = [], data = [], colors = [];


                var randomColorGenerator = function () {
                    return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };

                for (var i = 0; i < result.length; i = i + 2) {

                    labels.push(result[i]);
                    data.push(result[i + 1]);
                    colors.push(randomColorGenerator());

        }


                var chartData = {
            labels: labels,
            datasets: [
                      {
            label: label,
            backgroundColor: colors,
            data: data
        }
        ]
        };
                var opt = {
            events: false,
            tooltips: {
            enabled: false
        },
            hover: {
            animationDuration: 0
        },
            scales: {
            yAxes: [{
            ticks: {
            beginAtZero: true
        }
        }]
        },
            animation: {
            duration: 1,
            onComplete: function () {
                            var chartInstance = this.chart,
                                ctx = chartInstance.ctx;
                            ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'bottom';

                            this.data.datasets.forEach(function (dataset, i) {
                                var meta = chartInstance.controller.getDatasetMeta(i);
                                meta.data.forEach(function (bar, index) {
                                    var data = dataset.data[index];
                                    ctx.fillText(data, bar._model.x, bar._model.y - 5);
        });
        });
        }
        }
        };
                var ctx = document.getElementById("drivers-graph"),
                    myLineChart = new Chart(ctx, {
            type: 'bar',
            data: chartData,
            options: opt
        })

        });

        })
        
        
    </script>

                 </asp:View>

             <asp:View ID="ViewChangePassword" runat="server" >
               <asp:Label ID="LabelWrongPassword" runat="server" Text="Parolă greșită!" Visible="False"></asp:Label>
        <p>
            <asp:TextBox ID="TextBoxNewPassword" placeholder="Parolă nouă" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword"></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidatorPassword"  runat="server"
          ControlToValidate="TextBoxNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            
        </p>
                     <p>
            <asp:TextBox ID="TextBoxConfirmNewPassword" placeholder="Confirmă parola nouă" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword" ></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidatorConfirmPassword"  runat="server"
          ControlToValidate="TextBoxConfirmNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            <asp:Label ID="Label1" runat="server" Text="Password mismatch!" Visible="False" CssClass="Register_lbl"></asp:Label>
            <br/>
                         <asp:Label ID="LabelMismatch" runat="server" Text="Password mismatch!" Visible="False" CssClass="Register_lbl"></asp:Label>
                         </p>
                         <asp:Button ID="ButtonSave" runat="server" Text="Salvează" OnClick="ButtonSave_Click" CssClass="Main_btn"/>
        

                 </asp:View>

        </asp:MultiView>
                
            
      
    </div>
        
           <div class="Main_footer" runat="server">
            
            <asp:Button ID="ButtonLogout" runat="server" OnClick="ButtonLogout_Click" Text="Delogare" CausesValidation="false" cssClass="Main_logout_btn"/>
            </div>
    </div>
    </form>
        </div>
</body>
</html>
