<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Main.aspx.cs" Inherits="Main" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
    <link href="Theme/Style.css" rel="stylesheet" type="text/css" />
    <div class="Base">
    <form id="form1" runat="server" class="Main_Div">
    <div>
      <h1>
         <asp:Menu ID="Menu1" runat="server" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal" >
            <Items>
                <asp:MenuItem  Selected="True" Text="Pontează" Value="0"></asp:MenuItem>
                <asp:MenuItem  Text="Pontajele mele" Value="1"></asp:MenuItem>
                <asp:MenuItem  Text="Calendar" Value="2"></asp:MenuItem>
                <asp:MenuItem  Text="Rapoarte" Value="3"></asp:MenuItem>
                <asp:MenuItem  Text="Schimbă parola" Value="4"></asp:MenuItem>
                 
            </Items>
            <staticmenuitemstyle BorderWidth="10px" BorderColor="#6189df"  forecolor="Black" /> 
        </asp:Menu>
           </h1>   
      
    
         
           
        <div runat="server" id="ScrollList" class="Main_Menu_div">
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0" >
                
              
         <asp:View ID="ViewPontaje" runat="server" >

            

        
        <asp:GridView ID="gvProjects"  CssClass="grid" runat="server" AutoGenerateColumns="false"  RowStyle-Wrap="true" PageSize="10" AllowPaging="true" DataSourceID="SqlDataSourceLogs" OnRowCommand="GridView_RowCommand">

             <EmptyDataRowStyle CssClass="EmptyData" />
                <EmptyDataTemplate>

                    <div>
                        No Data Available
                    </div>

                    <script>
                        $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                    </script>

               </EmptyDataTemplate>

            <Columns>
              
                
                         
                
                <asp:TemplateField ShowHeader="False" HeaderText="Categorie proiect" ItemStyle-Width="50%">
                 <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelTextCategory(Eval("id_category")) %>' />
                         </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="name" HeaderText="Proiect"  ItemStyle-Width="55%" />

                 <asp:TemplateField ShowHeader="False" ItemStyle-Width="25%">
                    <ItemTemplate>
                        <asp:Button ID="ButtonLog" runat="server"   CommandArgument='<%# Eval("id") %>'  Text="Pontează" CssClass="Main_btn"></asp:Button>
                     </ItemTemplate>
                 </asp:TemplateField>

            </Columns>    
            
         </asp:GridView>
        
        
         <asp:SqlDataSource ID="SqlDataSourceLogs" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" SelectCommand="SELECT * FROM [Projects] order by id_category">
         </asp:SqlDataSource>
        
        </asp:View>

        <asp:View ID="ViewPontajeleMele" runat="server">
            
              

               <asp:GridView ID="GridViewPontajeleMele" runat="server" Width="1000px" CssClass="grid" PageSize="10" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AllowPaging="true" DataKeyNames="id" DataSourceID="SqlDataSourcePontajeleMele">
                   

                   
               <EmptyDataRowStyle CssClass="EmptyData" />
                <EmptyDataTemplate>

                    <div>
                        No Data Available
                    </div>

                    <script>
                        $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                    </script>

               </EmptyDataTemplate>
                   
                   
                   <Columns>

                      <asp:BoundField DataField="date" HeaderText="Data" DataFormatString="{0:dd-M-yyyy}" SortExpression="date" ItemStyle-Width="15%"/>
                      <asp:TemplateField ItemStyle-CssClass="TemplateFieldOneColumn" HeaderText="Proiect" ItemStyle-Width="25%">

                         <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelTextProject(Eval("id_project")) %>' />
                         </ItemTemplate>

                       </asp:TemplateField>

                        <asp:TemplateField ItemStyle-CssClass="TemplateFieldOneColumn" HeaderText="Tip activitate" ItemStyle-Width="25%">

                         <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelTextActivity(Eval("id_activity_type")) %>' />
                         </ItemTemplate>

                       </asp:TemplateField>
                       <asp:BoundField DataField="cantitate" HeaderText="Cantitate" SortExpression="cantitate" ItemStyle-Width="5%" />
                       <asp:BoundField DataField="hours" HeaderText="Ore" SortExpression="hours" ItemStyle-Width="5%"/>
                       <asp:BoundField DataField="observations" HeaderText="Observații" SortExpression="observations" ItemStyle-Width="35%"/>
                   
                       
                        
                      
                   </Columns>

               </asp:GridView>

                

               
              

               <asp:SqlDataSource ID="SqlDataSourcePontajeleMele" runat="server" ConnectionString="<%$ ConnectionStrings:PontajeConnectionString %>" 
                  DeleteCommand="delete from [Logs] where [id]=@id" >

               </asp:SqlDataSource>
              </asp:View>

            <asp:View ID="ViewCalendar" runat="server">
               
                <asp:Calendar ID="CalendarEvents"  OnDayRender="AttachEvents" runat="server" Width="100%" Height="100%" >
                    
         
        <SelectorStyle BackColor="#FFCC66"></SelectorStyle>
        <NextPrevStyle Font-Size="9pt" ForeColor="#FFFFCC"></NextPrevStyle>
        <DayHeaderStyle Height="1px" BackColor="#e5e5e9" Font-Names="Calibri"></DayHeaderStyle>
        <SelectedDayStyle Font-Bold="True" BackColor="#6189df"></SelectedDayStyle>
        <TitleStyle Font-Size="16pt" Font-Bold="True" ForeColor="White" BackColor="#6189df" Font-Names="Calibri"></TitleStyle>
        <OtherMonthDayStyle ForeColor="#e5e5e9"></OtherMonthDayStyle>
        <TodayDayStyle BackColor="#6189df" ForeColor="White"> </TodayDayStyle>
        <DayStyle BorderStyle="Solid" BorderColor="#e5e5e9"></DayStyle>
           
                    

                </asp:Calendar>
            
                   
            
            </asp:View>

            <asp:View ID="ViewReports" runat="server">

                <canvas id="projects-graph" width="800" height="500"></canvas>

                 
    <script>

      

        $(function () {
            $.getJSON("/api/user/<%= id_user %>", function (result) {
                var labels = [], data = [], colors = [];


                var randomColorGenerator = function () {
                    return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
                };

                for (var i = 0; i < result.length; i = i + 2) {

                    labels.push(result[i]);
                    data.push(result[i + 1]);
                    colors.push(randomColorGenerator());

                }


                var chartData = {
                    labels: labels,
                    datasets: [
                      {
                          label: 'Ore lucrate per proiect',
                          backgroundColor: colors,
                          data: data
                      }
                    ]
                };
                var opt = {
                    events: false,
                    tooltips: {
                        enabled: false
                    },
                    hover: {
                        animationDuration: 0
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    },
                    animation: {
                        duration: 1,
                        onComplete: function () {
                            var chartInstance = this.chart,
                                ctx = chartInstance.ctx;
                            ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'bottom';

                            this.data.datasets.forEach(function (dataset, i) {
                                var meta = chartInstance.controller.getDatasetMeta(i);
                                meta.data.forEach(function (bar, index) {
                                    var data = dataset.data[index];
                                    ctx.fillText(data, bar._model.x, bar._model.y - 5);
                                });
                            });
                        }
                    }
                };
                var ctx = document.getElementById("projects-graph"),
                    myLineChart = new Chart(ctx, {
                        type: 'bar',
                        data: chartData,
                        options: opt
                    })

            });

        })

        
    </script>
                
            </asp:View>

            <asp:View ID="ViewChangePassword" runat="server" >
               <asp:Label ID="LabelWrongPassword" runat="server" Text="Parolă greșită!" Visible="False"></asp:Label>
        <p>
            <asp:TextBox ID="TextBoxNewPassword" placeholder="Parolă nouă" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword"></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidatorConfirmPassword" runat="server"
          ControlToValidate="TextBoxNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            
        </p>
                     <p>
            <asp:TextBox ID="TextBoxConfirmNewPassword" placeholder="Confirmă parola" TextMode="Password" runat="server" CssClass="TextBox_ChangePassword" ></asp:TextBox>
            <asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server"
          ControlToValidate="TextBoxConfirmNewPassword"
          ErrorMessage="Obligatoriu!"
          ForeColor="Red">
        </asp:RequiredFieldValidator>
            <br/>
                         <asp:Label ID="LabelMismatch" runat="server" Text="Password mismatch!" Visible="False" CssClass="Register_lbl"></asp:Label>
                         </p>
                         <asp:Button ID="ButtonSave" runat="server" Text="Salvează" OnClick="ButtonSave_Click" CssClass="Main_btn"/>
        

                 </asp:View>

        </asp:MultiView>
                
            
      
    </div>
        
            <div class="Main_footer" runat="server">
            
            <asp:Button ID="ButtonLogout" runat="server" OnClick="ButtonLogout_Click" CausesValidation="false" Text="Delogare" cssClass="Main_logout_btn"/>
            </div>
    </div>
    </form>
        </div>
</body>
</html>
