//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ActivityType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ActivityType()
    {
        this.Logs = new HashSet<Log>();
    }

    public int id { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log> Logs { get; set; }
}

public partial class Car
{
    public int id { get; set; }
    public string number { get; set; }
}

public partial class Log
{
    public int id { get; set; }
    public int id_user { get; set; }
    public Nullable<int> id_project { get; set; }
    public Nullable<int> id_activity_type { get; set; }
    public Nullable<int> cantitate { get; set; }
    public System.DateTime date { get; set; }
    public int hours { get; set; }
    public string observations { get; set; }

    public virtual ActivityType ActivityType { get; set; }
    public virtual Project Project { get; set; }
    public virtual User User { get; set; }
}

public partial class Log_driver
{
    public int id { get; set; }
    public int id_user { get; set; }
    public int id_project { get; set; }
    public System.DateTime date { get; set; }
    public string vehicle_number { get; set; }
    public int km { get; set; }
    public int hours { get; set; }
    public string observations { get; set; }
    public Nullable<int> id_pass1 { get; set; }
    public Nullable<int> id_pass2 { get; set; }
    public Nullable<int> id_pass3 { get; set; }
    public Nullable<int> id_pass4 { get; set; }

    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
    public virtual User User2 { get; set; }
    public virtual User User3 { get; set; }
    public virtual Project Project { get; set; }
    public virtual User User4 { get; set; }
}

public partial class Project
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project()
    {
        this.Log_driver = new HashSet<Log_driver>();
        this.Logs = new HashSet<Log>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public int id_category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log> Logs { get; set; }
    public virtual ProjectCategory ProjectCategory { get; set; }
}

public partial class ProjectCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProjectCategory()
    {
        this.Projects = new HashSet<Project>();
    }

    public int id { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project> Projects { get; set; }
}

public partial class Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {
        this.Users = new HashSet<User>();
    }

    public int id { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Log_driver = new HashSet<Log_driver>();
        this.Log_driver1 = new HashSet<Log_driver>();
        this.Log_driver2 = new HashSet<Log_driver>();
        this.Log_driver3 = new HashSet<Log_driver>();
        this.Log_driver4 = new HashSet<Log_driver>();
        this.Logs = new HashSet<Log>();
    }

    public int id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string username { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public int id_role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver3 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log_driver> Log_driver4 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log> Logs { get; set; }
    public virtual Role Role { get; set; }
}
