//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Pontaje_firma_topografieEntities : DbContext
{
    public Pontaje_firma_topografieEntities()
        : base("name=Pontaje_firma_topografieEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ActivityType> ActivityTypes { get; set; }
    public virtual DbSet<Car> Cars { get; set; }
    public virtual DbSet<Log_driver> Log_driver { get; set; }
    public virtual DbSet<Log> Logs { get; set; }
    public virtual DbSet<ProjectCategory> ProjectCategories { get; set; }
    public virtual DbSet<Project> Projects { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<User> Users { get; set; }
}
